### ISSUE TITLE
Visualize the result while testing

### ISSUE THREAD

**Issue by jrcai** [FangyunWei/PointSetAnchor#5]
Hello,

Thanks for making your work open-source. I was trying to use --show argument when running test.py, but failed in dimensional mismatch, which seems caused by rescaling? I made the bbox displayed correctly, but not the masks. Could you please point me to a possible solution?  Thanks!

**Comment by FangyunWei** [comment]
> Hello,
> 
> Thanks for making your work open-source. I was trying to use --show argument when running test.py, but failed in dimensional mismatch, which seems caused by rescaling? I made the bbox displayed correctly, but not the masks. Could you please point me to a possible solution? Thanks!

Can you run dist_test.sh? We may not implement results visualization.

**Comment by jrcai** [comment]
Using dist_test.sh and test.py results in the same issue, but I found tools/draw_mask.py is useful. Thank you.
